package dev.hadesclient.mixin;

import dev.hadesclient.HadesClient;
import net.minecraft.client.MinecraftClient;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.screen.ScreenHandler;
import net.minecraft.screen.slot.Slot;
import net.minecraft.screen.slot.SlotActionType;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * Prevents inventory operations from involving locked player inventory slots.
 *
 * This operates at the ScreenHandler level rather than only at the GUI
 * mouse level, which means it catches the actual inventory operations
 * generated by Minecraft.
 */
@Mixin(ScreenHandler.class)
public abstract class ScreenHandlerMixin {

    @Shadow
    public abstract Slot getSlot(int index);

    /**
     * Intercept all slot operations.
     *
     * Minecraft uses onSlotClick for:
     *
     * PICKUP
     * QUICK_MOVE
     * SWAP
     * CLONE
     * THROW
     * QUICK_CRAFT
     * PICKUP_ALL
     */
    @Inject(
            method = "onSlotClick",
            at = @At("HEAD"),
            cancellable = true
    )
    private void hadesclient$protectLockedSlots(
            int slotIndex,
            int button,
            SlotActionType actionType,
            PlayerEntity player,
            CallbackInfo ci
    ) {

        /*
         * This protection is client-side.
         */
        if (!isClientPlayer(player)) {
            return;
        }

        /*
         * If there are no locks, there is nothing to check.
         */
        if (!HadesClient.slotLocks().hasAnyLocks()) {
            return;
        }

        /*
         * Ignore clicks outside the inventory.
         *
         * -999 is Minecraft's special outside-click value.
         */
        if (slotIndex < 0) {
            return;
        }

        /*
         * Find the slot being acted upon.
         */
        Slot clickedSlot;

        try {
            clickedSlot = this.getSlot(slotIndex);
        } catch (Exception ignored) {
            return;
        }

        if (clickedSlot == null) {
            return;
        }

        /*
         * If the clicked slot itself is locked,
         * absolutely nothing can happen to it.
         */
        if (HadesClient.slotLocks().isLocked(clickedSlot)) {
            ci.cancel();
            return;
        }

        /*
         * SWAP is special.
         *
         * Example:
         *
         * Locked inventory slot
         *        ↓
         * Press 1 while hovering another slot
         *        ↓
         * Minecraft attempts to swap with hotbar slot 0.
         *
         * We must therefore check the hotbar slot as well.
         */
        if (actionType == SlotActionType.SWAP) {

            int hotbarInventoryIndex = button;

            Slot hotbarSlot =
                    findPlayerInventorySlot(hotbarInventoryIndex);

            if (hotbarSlot != null
                    && HadesClient.slotLocks().isLocked(hotbarSlot)) {

                ci.cancel();
                return;
            }
        }

        /*
         * QUICK_MOVE / shift-click can move items between inventories.
         *
         * If the source is unlocked, Minecraft may attempt to insert
         * the item into a locked player slot.
         *
         * We therefore conservatively block QUICK_MOVE whenever any
         * locked player slot exists.
         *
         * This prevents shift-click from bypassing the lock.
         */
        if (actionType == SlotActionType.QUICK_MOVE) {

            if (HadesClient.slotLocks().hasAnyLocks()) {
                ci.cancel();
                return;
            }
        }

        /*
         * QUICK_CRAFT represents drag/quick-craft operations.
         *
         * Minecraft calls onSlotClick repeatedly while building
         * a quick-craft operation.
         *
         * If the target is unlocked, the drag may still include
         * locked slots later.
         *
         * We therefore block quick-craft whenever locks exist.
         *
         * This is intentionally conservative: protecting the locked
         * item is more important than allowing a drag operation.
         */
        if (actionType == SlotActionType.QUICK_CRAFT) {

            if (HadesClient.slotLocks().hasAnyLocks()) {
                ci.cancel();
            }
        }

        /*
         * PICKUP_ALL is Minecraft's double-click "collect matching
         * items" operation.
         *
         * It can scan multiple slots, including locked slots.
         *
         * Block it whenever locks exist so a double-click cannot
         * pull a locked item into the cursor.
         */
        if (actionType == SlotActionType.PICKUP_ALL) {

            if (HadesClient.slotLocks().hasAnyLocks()) {
                ci.cancel();
            }
        }

        /*
         * THROW is Q / Ctrl+Q.
         *
         * The clicked-slot check above catches throwing directly
         * from a locked slot.
         */
    }

    /**
     * Find a player's hotbar slot by PlayerInventory index.
     *
     * PlayerInventory hotbar indices are 0-8.
     */
    private Slot findPlayerInventorySlot(int inventoryIndex) {

        MinecraftClient client = MinecraftClient.getInstance();

        if (client.player == null) {
            return null;
        }

        /*
         * Search the current screen handler's slots.
         *
         * We do this rather than assuming a particular screen-handler
         * slot ID because different containers arrange player slots
         * differently.
         */
        ScreenHandler handler = (ScreenHandler) (Object) this;

        for (Slot slot : handler.slots) {

            if (slot.inventory == client.player.getInventory()
                    && slot.getIndex() == inventoryIndex) {

                return slot;
            }
        }

        return null;
    }

    /**
     * Make sure we only protect the actual client player.
     */
    private boolean isClientPlayer(PlayerEntity player) {

        MinecraftClient client =
                MinecraftClient.getInstance();

        return client.player != null
                && player == client.player;
    }
}
