package dev.hadesclient.mixin;

import dev.hadesclient.HadesClient;
import net.minecraft.client.MinecraftClient;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.screen.ScreenHandler;
import net.minecraft.screen.slot.Slot;
import net.minecraft.screen.slot.SlotActionType;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * Protects locked player-inventory slots at the ScreenHandler level.
 *
 * This catches inventory operations after they have been generated by
 * Minecraft's GUI, rather than relying only on mouse clicks.
 */
@Mixin(ScreenHandler.class)
public abstract class ScreenHandlerMixin {

    @Shadow
    public abstract Slot getSlot(int index);

    /**
     * Intercept Minecraft inventory operations.
     */
    @Inject(
            method = "onSlotClick",
            at = @At("HEAD"),
            cancellable = true
    )
    private void hadesclient$protectLockedSlots(
            int slotIndex,
            int button,
            SlotActionType actionType,
            PlayerEntity player,
            CallbackInfo ci
    ) {

        /*
         * Only protect the actual client player's inventory.
         */
        MinecraftClient client = MinecraftClient.getInstance();

        if (client.player == null || player != client.player) {
            return;
        }

        /*
         * -999 means the mouse clicked outside the inventory.
         */
        if (slotIndex < 0) {
            return;
        }

        /*
         * Get the slot Minecraft is currently operating on.
         */
        Slot clickedSlot;

        try {
            clickedSlot = this.getSlot(slotIndex);
        } catch (Exception ignored) {
            return;
        }

        if (clickedSlot == null) {
            return;
        }

        /*
         * ---------------------------------------------------------
         * DIRECT INTERACTION
         * ---------------------------------------------------------
         *
         * Left click
         * Right click
         * Q
         * Ctrl+Q
         * etc.
         *
         * If the slot being acted on is locked, cancel it.
         */
        if (HadesClient.slotLocks().isLocked(clickedSlot)) {
            ci.cancel();
            return;
        }

        /*
         * ---------------------------------------------------------
         * HOTBAR SWAP
         * ---------------------------------------------------------
         *
         * Pressing 1-9 while hovering a slot uses SWAP.
         *
         * button = hotbar index:
         *
         * 0 = 1
         * 1 = 2
         * ...
         * 8 = 9
         *
         * We must protect the hotbar slot too.
         */
        if (actionType == SlotActionType.SWAP) {

            Slot hotbarSlot =
                    findPlayerInventorySlot(button);

            if (hotbarSlot != null
                    && HadesClient.slotLocks().isLocked(hotbarSlot)) {

                ci.cancel();
                return;
            }
        }

        /*
         * ---------------------------------------------------------
         * QUICK MOVE / SHIFT CLICK
         * ---------------------------------------------------------
         *
         * A shift-click starts with the clicked slot.
         *
         * If the clicked slot is locked, the check above already
         * cancelled it.
         *
         * We deliberately do NOT cancel every QUICK_MOVE when a
         * lock exists, because that would make one locked slot
         * disable all shift-clicking.
         *
         * For now, the locked-slot itself is protected.
         */
        if (actionType == SlotActionType.QUICK_MOVE) {
            return;
        }

        /*
         * ---------------------------------------------------------
         * THROW
         * ---------------------------------------------------------
         *
         * Q / Ctrl+Q from a locked slot was already caught by the
         * clicked-slot check above.
         */
        if (actionType == SlotActionType.THROW) {
            return;
        }

        /*
         * ---------------------------------------------------------
         * PICKUP_ALL
         * ---------------------------------------------------------
         *
         * Double-click can collect matching items from multiple
         * slots.
         *
         * We handle this separately below.
         */
        if (actionType == SlotActionType.PICKUP_ALL) {

            /*
             * If the clicked slot isn't locked, vanilla can still
             * scan other slots and potentially collect a locked item.
             *
             * For the first working version, don't allow PICKUP_ALL
             * while locked slots exist.
             *
             * This is intentionally conservative.
             */
            if (!HadesClient.slotLocks().lockedSlots().isEmpty()) {
                ci.cancel();
            }

            return;
        }

        /*
         * ---------------------------------------------------------
         * QUICK CRAFT / DRAG
         * ---------------------------------------------------------
         *
         * Dragging is handled as a multi-step operation by Minecraft.
         *
         * We currently prevent quick-craft whenever locked slots exist
         * so a drag cannot bypass the lock.
         */
        if (actionType == SlotActionType.QUICK_CRAFT) {

            if (!HadesClient.slotLocks().lockedSlots().isEmpty()) {
                ci.cancel();
            }
        }
    }

    /**
     * Find a player's inventory slot using the PlayerInventory index.
     *
     * This is important because ScreenHandler slot IDs are NOT the
     * same thing as PlayerInventory indices.
     */
    private Slot findPlayerInventorySlot(int inventoryIndex) {

        MinecraftClient client =
                MinecraftClient.getInstance();

        if (client.player == null) {
            return null;
        }

        ScreenHandler handler =
                (ScreenHandler) (Object) this;

        for (Slot slot : handler.slots) {

            if (slot.inventory == client.player.getInventory()
                    && slot.getIndex() == inventoryIndex) {

                return slot;
            }
        }

        return null;
    }
}
